[profile.default]
src = "src"
out = "out"
script = "script"
cache = true
cache_path = "cache"
build_info = true
build_info_path = "out/build-info"
libs = ["lib"]
sender = "0xD70A2e6eACbdeDA77a5d4bBAE3bC70239A0e088f"
force = false
optimizer = true
verbosity = 5
auto_detect_remappings = false
optimizer_runs = 999999
evm_version = "london"
bytecode_hash = "ipfs"
extra_output = ['storageLayout']
extra_output_files = ["metadata"]
fs_permissions = [
  { "access" = "read-write", "path" = "./cache"},
  { "access" = "read-write", "path" = "./out" },
  { "access" = "read-write", "path" = "./deployments/" },
  { "access" = "read", "path" = "./script/input/" },
  { "access" = "read", "path" = "./lib/safe-deployments/src/assets/" },
  { "access" = "read", "path" = "./sphinx.lock" },
]
allow_paths = ["../.."]

[rpc_endpoints]
## testnets
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
darwinia_koi = "https://koi-rpc.darwinia.network"
sepolia = "https://rpc.ankr.com/eth_sepolia"
taiko_hekla = "https://rpc.hekla.taiko.xyz"
tanssi_pangoro = "https://fraa-flashbox-2871-rpc.a.stagenet.tanssi.network"

## mainnets
ethereum = "https://rpc.ankr.com/eth"
darwinia = "https://darwinia-rpc.itering.io"
crab = "https://crab-rpc.itering.io"
arbitrum = "https://arb1.arbitrum.io/rpc"
blast = "https://rpc.blast.io"
polygon = "https://polygon-mainnet.blastapi.io/${BLAST_KEY}"
moonbeam = "https://rpc.api.moonbeam.network"
morph = "https://rpc.morphl2.io"
