[profile.default]
src = "src"
out = "out"
libs = ["lib"]
sender = "0xD70A2e6eACbdeDA77a5d4bBAE3bC70239A0e088f"
force = false
optimizer = true
auto_detect_remappings = false
optimizer_runs = 999999
evm_version = "london"
bytecode_hash = "ipfs"
extra_output = ['storageLayout']
extra_output_files = ["metadata"]
fs_permissions = [
  { "access" = "read-write", "path" = "./cache"},
  { "access" = "read-write", "path" = "./out" },
  { "access" = "read-write", "path" = "./deployments/" },
]

[rpc_endpoints]
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
pangolin = "https://pangolin-rpc.darwinia.network"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
taiko_katla = "https://rpc.katla.taiko.xyz"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}"}
arbitrum-sepolia = { key = "${ETHERSCAN_ARBITRUM_KEY}"}
pangolin = { key = "", url = "https://pangolin.api.subscan.io/api/scan/evm/contract/verifysource" }
taiko-katla = { key = "", url = "https://api.routescan.io/v2/network/testnet/evm/1/etherscan/api"}
