[local]
name = "Arbitrum One Sepolia"
chainId = 421614
chainAlias = "arbitrum_sepolia"
rpcUrl = "https://sepolia-rollup.arbitrum.io/rpc" 

[remote]
chains = [11155111,43]

[ormp]
[ormp.oracle]
[ormp.oracle.11155111]
fee = 27500000000000000

[ormp.oracle.43]
fee = 50000000000

[ormp.oracle.167008]
fee = 27500000000000

[ormp.relayer]
[ormp.relayer.11155111]
dstPriceRatio = 10000000000 
dstGasPriceInWei = 25000000000
baseGas = 120000
gasPerByte = 16

[ormp.relayer.43]
dstPriceRatio = 13888 
dstGasPriceInWei = 160000000000 
baseGas = 200000
gasPerByte = 16

[ormp.relayer.167008]
dstPriceRatio = 10000000000 
dstGasPriceInWei = 10
baseGas = 120000
gasPerByte = 16
