name: Sphinx Dry Run
env:
    SPHINX_API_KEY: ${{ secrets.SPHINX_API_KEY }}
    BLAST_KEY: ${{ secrets.BLAST_KEY }}

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  sphinx-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-7f0f5b4c1aa75dc4fd2eb15aca9757491d885902
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      # - name: Install Sphinx Solidity Library
      #   run: yarn sphinx install
      - name: Skip
        run: npx sphinx propose ./script/Proposal.s.sol --dry-run --networks mainnets --targetContract Proposal --skip
      - name: Dry Run
        run: npx sphinx propose ./script/Proposal.s.sol --dry-run --networks mainnets --targetContract Proposal
